git:
  depth: 500

notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=mtgupf/essentia-builds:manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=mtgupf/essentia-builds:manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build_wheels.sh
  - ls wheelhouse/

deploy:
  - provider: pypi
    server: https://testpypi.python.org/pypi
    distributions: sdist bdist_wheel
    user: dbogdanov
    password:
      secure: 4M7A1uxjdAmkyR6LrLsJcQIxN5xQiLK33hiTQO9jU3sUIO0aqxVK7OWSMuepG0TW+D1tV+8nMWPCFsXrW/ibrFBzhbRKOOW7FK8YreaA/Iat494qW4EtPWk2eXgCSMoioSzi4K3EPvYNfaIjkzqAlxUfJsACrBI70YdL7VRjfyo=
    on:
      branch: master
